version: "3.9"

services:

  devices-wiremock-api:
    image: wiremock/wiremock:2.32.0
    ports:
      - "82:8080"
    command:
      - "--global-response-templating"
    volumes:
      - ./wiremock/devices-api:/home/wiremock

#  bar-api:
#    image: wiremock/wiremock:2.32.0
#    ports:
#      - "8080"
#    command:
#      - "--global-response-templating"
#    volumes:
#      - ./wiremock/bar-api:/home/wiremock